### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\AI\\InstantIR/adapter.pt' Press any key to continue . . .

### ISSUE THREAD

**Issue by jian27com** [JY-Joy/InstantIR#2]
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\AI\\InstantIR/adapter.pt'
Press any key to continue . . .
这个adapter.pt文件找不到？是什么文件？

**Comment by JY-Joy** [comment]
这是InstantIR的模型文件，你可以在[Hugging Face](https://huggingface.co/InstantX/InstantIR)上下载，或者用我们README里提供的python脚本

```py
from huggingface_hub import hf_hub_download
hf_hub_download(repo_id="InstantX/InstantIR", filename="models/adapter.pt", local_dir=".")
```
