### ISSUE TITLE
demo code is not working

### ISSUE THREAD

**Issue by sipie800** [JY-Joy/InstantIR#3]
error is something like this during piepline sampler:
mat1 and mat2 must have the same dtype. got half and float. 
some of your modules must be initialized to fp32, though others are fp16. there are too many modules that I can't check. maybe it's due to my existing SDXL weight are fp32 though your pipeline is explicitly fp16. I'm not sure. I have deleted the repo. just report for your noticing.

**Comment by JY-Joy** [comment]
Thanks for your trying and your report. I'm sorry we've transferred the repo to our official account, please check this [repo](https://x.com/notifications) for our latest version. I will update this repo in case of future troubles.
